version: "3.9"

services:
  docs-builder-cicd:
    image: cotswoldsmaker/bmi-calc:latest
    container_name: docs-builder-cicd
    restart: "no"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOW_HOSTS=${ALLOW_HOSTS}
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ../:/bmi-calc
    working_dir: /bmi-calc/app
    entrypoint: bash PID_1_cicd.sh

# DJANGO_SECRET_KEY='12341234afqwer' ALLOW_HOSTS='["0.0.0.0","localhost"]' docker-compose up --exit-code-from docs-builder-cicd