site_name: Digital Clinical Safety Platform
site_description: Clinical hazard mitigation and reporting system

# TODO #42 - Essential to work with "X-Accel-Redirect" and "view_docs"
use_directory_urls: false

plugins:
  - macros
  - include-markdown:
      dedent: true
  - mkdocstrings:
      handlers:
        python:
          paths: [../app/bmi-calc/app, ../app/bmi-calc/app/functions]

theme:
  name: material
  logo: static/assets/favicon/favicon.ico
  favicon: static/assets/favicon/favicon.ico

  features:
    - navigation.instant
    # uncomment the below two lines for Tabbed navigation (along the header bar)
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    code: Roboto Mono

extra:
  generator: false


# Copyright information which is shown in the footer
copyright: Clinicians-who-code

# these lines configure the 'GitHub repo' widget on the top right
# uncomment to enable
repo_url: https://github.com/clinicians-who-code/clinical-safety-hazard-documentation
repo_name: clinical-safety-hazard-documentation


# Navigation structure
#nav:
#  - Home: "index.md"
#  - "clinical-safety-management-system.md"
#  - "clinical-safety-management-plan.md"
#  - "clinical-safety-case-report.md"
#  - "hazard-log.md"
#  - "business-continuity.md"
#  - "security.md"
#  - "third-party-tools-safety-assmt.md"
#  - "medical-device.md"
#  - "download.md"
#  - "contact.md"
#  - "license.md"




# mkdocs plugins
#plugins:
#  - git-committers:
#      repository: https://github.com/clinicians-who-code/clinical-safety-hazard-documentation
#      branch: main
#      enabled: !ENV [ENABLE_GIT_COMMITTERS, false] # makes Git Committers optional
#  - git-revision-date-localized:
#      enable_creation_date: true
#  - search
  #- with-pdf:
      #cover: false
      #back_cover: true
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      ##output_path: pdf/{{cookiecutter.__project_slug}}-clinical-safety-management-file.pdf
      ##enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true
  # TODO might remove this
  - pymdownx.extra


extra_css:
  - static/css/dcsp_mkdocs.css

extra_javascript:
  - static/js/dcsp_mkdocs.js

#extra:
  #project_slug: {{ cookiecutter.__project_slug }}

  # uncomment to add social icons
  # social:
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/exampleorgstwitter
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/exampleorgsgithub

INHERIT: ./placeholders.yml