site_name: Digital Clinical Safety Platform
site_description: Clinical hazard mitigation and reporting system

# Essential to work with "X-Accel-Redirect" and "view_docs"
use_directory_urls: false

plugins:
  - macros
  - include-markdown:
      dedent: true

theme:
  name: material
  palette:
    scheme: slate
    media: "(prefers-color-scheme: dark)"
    icon: material/brightness-4
  logo: static/assets/favicon/favicon.ico
  favicon: static/assets/favicon/favicon.ico

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.expand

  font:
    code: Roboto Mono

extra:
  generator: false


# Copyright information which is shown in the footer
copyright: Clinicians-who-code

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true
  # TODO might remove this
  - pymdownx.extra


extra_css:
  - static/css/dcsp_mkdocs.css

extra_javascript:
  - static/js/dcsp_mkdocs.js

INHERIT: ./placeholders.yml